package a;

/* JADX INFO: loaded from: D:\下载\Claude Code\scene_decompile\extracted\classes.dex */
public enum aa0 {
    POWER_CONNECTED,
    POWER_DISCONNECTED,
    BATTERY_LOW,
    BATTERY_CAPACITY_CHANGED,
    BATTERY_CHANGED,
    BATTERY_FULL,
    CHARGE_CONFIG_CHANGED,
    SCREEN_ON,
    SCREEN_OFF,
    APP_SWITCH,
    BOOT_COMPLETED,
    TIMER,
    ACCESSIBILITY_SERVICE,
    SERVICE_DEBUG,
    SERVICE_UPDATE,
    STATE_RESUME,
    SCENE_MODE_ACTION,
    SCENE_NOTIFY_UPDATE,
    SCENE_CONFIG,
    SCENE_APP_CONFIG,
    DAEMON_FRAME_TIME,
    DAEMON_SCENE_NOTIFY
}
